//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pan.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.57")]
        public double PCColon {
            get {
                return ((double)(this["PCColon"]));
            }
            set {
                this["PCColon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.57")]
        public double PCCandeal {
            get {
                return ((double)(this["PCCandeal"]));
            }
            set {
                this["PCCandeal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.57")]
        public double PCPicos {
            get {
                return ((double)(this["PCPicos"]));
            }
            set {
                this["PCPicos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double PCAnticrisis {
            get {
                return ((double)(this["PCAnticrisis"]));
            }
            set {
                this["PCAnticrisis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.27")]
        public double PCAVerano {
            get {
                return ((double)(this["PCAVerano"]));
            }
            set {
                this["PCAVerano"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public double PCPistolas {
            get {
                return ((double)(this["PCPistolas"]));
            }
            set {
                this["PCPistolas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.43")]
        public double PCIntegral {
            get {
                return ((double)(this["PCIntegral"]));
            }
            set {
                this["PCIntegral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.43")]
        public double PCSinSal {
            get {
                return ((double)(this["PCSinSal"]));
            }
            set {
                this["PCSinSal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.37")]
        public double PCMejorena {
            get {
                return ((double)(this["PCMejorena"]));
            }
            set {
                this["PCMejorena"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.54")]
        public double PCMGrande {
            get {
                return ((double)(this["PCMGrande"]));
            }
            set {
                this["PCMGrande"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.37")]
        public double PCNatural {
            get {
                return ((double)(this["PCNatural"]));
            }
            set {
                this["PCNatural"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.24")]
        public double PCBarrita {
            get {
                return ((double)(this["PCBarrita"]));
            }
            set {
                this["PCBarrita"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.85")]
        public double PVColon {
            get {
                return ((double)(this["PVColon"]));
            }
            set {
                this["PVColon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.85")]
        public double PVCandeal {
            get {
                return ((double)(this["PVCandeal"]));
            }
            set {
                this["PVCandeal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.85")]
        public double PVPicos {
            get {
                return ((double)(this["PVPicos"]));
            }
            set {
                this["PVPicos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double PVAnticrisis {
            get {
                return ((double)(this["PVAnticrisis"]));
            }
            set {
                this["PVAnticrisis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public double PVAVerano {
            get {
                return ((double)(this["PVAVerano"]));
            }
            set {
                this["PVAVerano"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.65")]
        public double PVPistolas {
            get {
                return ((double)(this["PVPistolas"]));
            }
            set {
                this["PVPistolas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.65")]
        public double PVIntegral {
            get {
                return ((double)(this["PVIntegral"]));
            }
            set {
                this["PVIntegral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.65")]
        public double PVSinSal {
            get {
                return ((double)(this["PVSinSal"]));
            }
            set {
                this["PVSinSal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.55")]
        public double PVMejorena {
            get {
                return ((double)(this["PVMejorena"]));
            }
            set {
                this["PVMejorena"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public double PVMGrande {
            get {
                return ((double)(this["PVMGrande"]));
            }
            set {
                this["PVMGrande"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.55")]
        public double PVNatural {
            get {
                return ((double)(this["PVNatural"]));
            }
            set {
                this["PVNatural"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.35")]
        public double PVBarrita {
            get {
                return ((double)(this["PVBarrita"]));
            }
            set {
                this["PVBarrita"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Colon")]
        public string Pan1 {
            get {
                return ((string)(this["Pan1"]));
            }
            set {
                this["Pan1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Candeal")]
        public string Pan2 {
            get {
                return ((string)(this["Pan2"]));
            }
            set {
                this["Pan2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Picos")]
        public string Pan3 {
            get {
                return ((string)(this["Pan3"]));
            }
            set {
                this["Pan3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Anticrisis")]
        public string Pan4 {
            get {
                return ((string)(this["Pan4"]));
            }
            set {
                this["Pan4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A.Verano")]
        public string Pan5 {
            get {
                return ((string)(this["Pan5"]));
            }
            set {
                this["Pan5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pistolas")]
        public string Pan6 {
            get {
                return ((string)(this["Pan6"]));
            }
            set {
                this["Pan6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Integral")]
        public string Pan7 {
            get {
                return ((string)(this["Pan7"]));
            }
            set {
                this["Pan7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sin Sal")]
        public string Pan8 {
            get {
                return ((string)(this["Pan8"]));
            }
            set {
                this["Pan8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mejoreña")]
        public string Pan9 {
            get {
                return ((string)(this["Pan9"]));
            }
            set {
                this["Pan9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M.Grande")]
        public string Pan10 {
            get {
                return ((string)(this["Pan10"]));
            }
            set {
                this["Pan10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Natural")]
        public string Pan11 {
            get {
                return ((string)(this["Pan11"]));
            }
            set {
                this["Pan11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Barrita")]
        public string Pan12 {
            get {
                return ((string)(this["Pan12"]));
            }
            set {
                this["Pan12"] = value;
            }
        }
    }
}
